# Generated by Django 4.1 on 2023-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color_size_alter_product_available_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_color',
            field=models.ManyToManyField(blank=True, null=True, related_name='available_color', to='shop.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_size',
            field=models.ManyToManyField(blank=True, null=True, related_name='available_size', to='shop.size'),
        ),
    ]
