# Generated by Django 4.1 on 2023-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_available_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dicount_price',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_color',
            field=models.ManyToManyField(blank=True, related_name='available_color', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=models.ManyToManyField(blank=True, related_name='available_size', to='shop.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
