# Generated by Django 4.1 on 2023-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_dicount_price_alter_product_available_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount_price',
            field=models.IntegerField(blank=True),
        ),
    ]
