# Generated by Django 4.1 on 2023-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_dicount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
